// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/3/2026, 5:17:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/hvekriya/Documents/git/vue-balkrishna-nursery/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/plugins/**/*.{js,ts,mjs}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/composables/**/*.{js,ts,mjs}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/utils/**/*.{js,ts,mjs}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hvekriya/Documents/git/vue-balkrishna-nursery/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;